services:
  - type: web
    name: insomnia-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 10005"
    envVars:
      - key: PYTHON_ENV
        value: "production"
